### PR TITLE
fix(map): cast all amount values to bigint

### LINKED ISSUE #700: Account crediting doesn't seem to add correctly
Pfry starts with initial balance of 0.01 USD.

After receiving payment of 8.71 USD, balance shows 18.71 USD.

### PR DESCRIPTION
**Pull request by sabineschaller**
## Changes proposed in this pull request

- fix crediting on MAP by typecasting all payment amount values to bigint

## Context

- fixes #700 

## Checklist

- [x] Related issues linked using `fixes #number`
- [ ] Tests added/updated
- [ ] Documentation added
- [x] Make sure that all checks pass

### CODE REVIEW

File: packages/mock-account-provider/app/routes/webhooks.ts [hunk 1]
```diff
@@ -63,9 +63,9 @@ export async function handleOutgoingPaymentCompletedFailed(wh: WebHook) {
   const amtSend = payment['sendAmount'] as Amount
   const amtSent = payment['sentAmount'] as Amount
```
Comment (wilsonianb) [inline packages/mock-account-provider/app/routes/webhooks.ts:64]: I think `Amount`'s `value` type should be changed from `bigint` to `string`
https://github.com/interledger/rafiki/blob/603df09615a2f458227baf3e23f99b3a0b103921/packages/mock-account-provider/app/routes/webhooks.ts#L23

and/or maybe map could use a:
https://github.com/interledger/rafiki/blob/603df09615a2f458227baf3e23f99b3a0b103921/packages/backend/src/open_payments/amount.ts#L13-L19

**Review by mkurapov — COMMENTED** [review]
Looks good after type on the `Amount` updated

**Review by wilsonianb — APPROVED** [review]
