### PR TITLE
fix: bruno collection for open payments examples

### LINKED ISSUE #3408: [Multi-Tenant] Fix Bruno Collection in Multi-Tenancy Feature branch
There are a few requests in the Bruno collection that are missing the additional `tenantId` in the path, or in the GraphQL input.

### PR DESCRIPTION
**Pull request by njlie**
## Changes proposed in this pull request

- Fixes bugs for Open Payments Examples and Rafiki Admin API requests in the Bruno Collection that were introduced by Multi-Tenancy.

## Context

Fixes #3408.

I tried to keep the fixes contained to issues that were introduced via Multi-Tenancy. There are some bugs that are also present in main.

## Checklist

- [ ] Related issues linked using `fixes #number`
- [ ] Tests added/updated
- [ ] Make sure that all checks pass
- [ ] Bruno collection updated (if necessary)
- [ ] Documentation issue created with `user-docs` label (if necessary)
- [ ] OpenAPI specs updated (if necessary)

### CODE REVIEW

File: bruno/collections/Rafiki/scripts.js [hunk 1]
```diff
@@ -106,7 +106,7 @@ const scripts = {
     return `t=${timestamp}, v${version}=${digest}`
   },
 
-  addApiSignatureHeader: function (packageName) {
+  addApiSignatureHeader: function (packageName, instance) {
```
Comment (mkurapov) [inline bruno/collections/Rafiki/scripts.js:109]: In `loadWalletAddressIdsIntoVariables`, we also need to pass in `tenant-id` header. Otherwise, the Examples > Admin API requests don't work where we use `loadWalletAddressIdsIntoVariables`
