### PR TITLE
fix(backend): remove wallet address from OP response id and fix receiver service

### LINKED ISSUE #2098: Remove wallet address from path of URL returned in create incoming payment response's `id` field

### LINKED ISSUE #2100: GET /incoming-payment not able to find incoming payment in db
Even though incoming-payment creation is successful and a row is added in the `incomingPayments` table, `GET /incoming-payments` is not able to retrieve it. This is also impeding creating quotes as well.

### LINKED ISSUE #2109: `POST /quotes` cannot retrieve incoming payment
Even with `GET /incoming-payments/:id` fixed there is still an issue retrieving it during quote creation. It might be due to confusion between using the public and private version of that endpoint.

### PR DESCRIPTION
**Pull request by sabineschaller**
## Changes proposed in this pull request

- removes wallet address from id in OP responses (incoming payment, quote, outgoing payment)
- adds auth server url to public incoming payment response
- fixes receiver service to get public incoming payment instead of wallet address to figure out where to find the auth server
- fixes getting the wallet address on resource GET requests through the wallet address middleware

## Context

- fixes #2098 
- fixes #2109
- fixes #2100 

## Checklist

- [ ] Related issues linked using `fixes #number`
- [ ] Tests added/updated
- [ ] Documentation added
- [ ] Make sure that all checks pass
- [ ] Postman collection updated

### CODE REVIEW

File: packages/backend/src/app.ts [hunk 1]
```diff
@@ -477,6 +477,7 @@ export class App {
     // Read incoming payment
     router.get<DefaultState, SubresourceContextWithAuthenticatedStatus>(
       '/incoming-payments/:id',
+      createWalletAddressMiddleware(),
```
Comment (mkurapov) [inline packages/backend/src/app.ts:480]: If this middleware is already fetching the resources, does it make sense to also then call `incomingPaymentRoutes.get`? 

(applies to all of them)

File: packages/backend/src/open_payments/wallet_address/middleware.ts [hunk 2]
```diff
@@ -10,20 +10,56 @@ export function createWalletAddressMiddleware() {
...
+    if (ctx.method === 'GET') {
+      if (ctx.path && ctx.path.startsWith('/incoming-payments')) {
+        const incomingPaymentService = await ctx.container.use(
+          'incomingPaymentService'
+        )
+        const incomingPayment = await incomingPaymentService.get({
+          id: ctx.params.id
+        })
+        if (!incomingPayment || !incomingPayment.walletAddress) {
+          ctx.throw(401)
```
Comment (mkurapov) [inline packages/backend/src/open_payments/wallet_address/middleware.ts:22]: 401 as to not give away whether the resource exists or not?

File: packages/backend/src/open_payments/wallet_address/middleware.ts [hunk 3]
```diff
@@ -10,20 +10,56 @@ export function createWalletAddressMiddleware() {
...
-    if (
-      ctx.path === '/incoming-payments' ||
-      ctx.path === '/outgoing-payments' ||
-      ctx.path === '/quotes'
-    ) {
-      if (ctx.method === 'GET') {
-        ctx.walletAddressUrl = ctx.query['wallet-address'] as string
-      } else if (ctx.method === 'POST') {
-        ctx.walletAddressUrl = (ctx.request.body as CreateBody).walletAddress
+    if (ctx.method === 'GET') {
```
Comment (mkurapov) [inline packages/backend/src/open_payments/wallet_address/middleware.ts:13]: We should break this up into multiple middlewares or at least separate functions in this file

File: packages/backend/src/open_payments/wallet_address/middleware.ts
Comment (BlairCurrey) [inline packages/backend/src/open_payments/wallet_address/middleware.ts:1]: I take it the changes here mean we can remove the wallet address from body/query params in the open payments spec for `/quotes`, `/incoming-payments`, `/outgoing-payments`, correct?

File: packages/backend/src/app.ts (hunk 1 above)
Comment (mkurapov) [reply packages/backend/src/app.ts:480]: We _could_ (this isn't great per se) store the fetched resource right on the context, and the skip the second lookup if we already have something defined in the ctx

**Review by mkurapov — COMMENTED** [review]
first pass

**Comment by mkurapov** [comment]
@BlairCurrey 
> I take it the changes here mean we can remove the wallet address from body/query params in the open payments spec for /quotes, /incoming-payments, /outgoing-payments, correct? Since we're just getting it via the resource id.

We still need it, during resource creation we don't have the resource id yet so we need a way to specify for which walletAddress the request is for

Likewise when we are GETting a list of resources, we don't have just a single resource to go off of

File: packages/backend/src/app.ts (hunk 1 above)
Comment (sabineschaller) [reply packages/backend/src/app.ts:480]: Please create issue for that @mkurapov

File: packages/backend/src/open_payments/wallet_address/middleware.ts (hunk 2 above)
Comment (sabineschaller) [reply packages/backend/src/open_payments/wallet_address/middleware.ts:29]: I wasn't really thinking that through but I think that counts as reasoning ;-)

File: packages/backend/src/open_payments/wallet_address/middleware.ts (hunk 3 above)
Comment (sabineschaller) [reply packages/backend/src/open_payments/wallet_address/middleware.ts:13]: Later. Please create issue 😉

File: packages/backend/src/open_payments/receiver/service.ts [hunk 4]
```diff
@@ -232,23 +225,35 @@ async function getLocalIncomingPayment({
...
+    url = `http://${parsedUrl.hostname}${parsedUrl.pathname}`
+  } else {
+    url = incomingPaymentUrl
+  }
+  const publicIncomingPaymentResponse = await fetch(url)
+  if (!publicIncomingPaymentResponse.ok) {
+    return undefined
+  }
+  const publicIncomingPayment = await publicIncomingPaymentResponse.json()
+  if (!publicIncomingPayment || !publicIncomingPayment.authServer) {
```
[the remark this answers is not in the document]
Comment (sabineschaller) [reply packages/backend/src/open_payments/receiver/service.ts:252]: Not yet. It also needs to be added to the spec. Once we have that, we can use the op sdk

File: packages/backend/src/open_payments/payment/incoming/routes.ts [hunk 5]
```diff
@@ -73,10 +73,11 @@ async function getIncomingPaymentPublic(
   try {
     const incomingPayment = await deps.incomingPaymentService.get({
       id: ctx.params.id,
-      client: ctx.accessAction === AccessAction.Read ? ctx.client : undefined,
-      walletAddressId: ctx.walletAddress.id
+      client: ctx.accessAction === AccessAction.Read ? ctx.client : undefined
     })
-    ctx.body = incomingPayment?.toPublicOpenPaymentsType()
+    ctx.body = incomingPayment?.toPublicOpenPaymentsType(
+      deps.config.authServerGrantUrl
```
Comment (njlie) [inline packages/backend/src/open_payments/payment/incoming/routes.ts:79]: Would there ever be a reason we'd need to return this in the private incoming payment response as well?

File: packages/backend/src/open_payments/receiver/service.ts (hunk 4 above)
[the remark this answers is not in the document]
Comment (BlairCurrey) [reply packages/backend/src/open_payments/receiver/service.ts:252]: https://github.com/interledger/rafiki/issues/2119

File: packages/backend/src/open_payments/receiver/service.ts [hunk 6]
```diff
@@ -232,23 +225,35 @@ async function getLocalIncomingPayment({
...
   deps: ServiceDependencies,
-  walletAddressUrl: string
+  incomingPaymentUrl: string
 ): Promise<Grant | undefined> {
-  const walletAddress = await deps.openPaymentsClient.walletAddress.get({
-    url: walletAddressUrl
-  })
-  if (!walletAddress) {
+  // TODO: replace with OP client method
+  // const publicIncomingPayment =
```
Comment (njlie) [inline packages/backend/src/open_payments/receiver/service.ts:238]: nit: remove comment?

File: packages/backend/src/open_payments/wallet_address/middleware.ts [hunk 7]
```diff
@@ -10,20 +10,63 @@ export function createWalletAddressMiddleware() {
...
+      if (
+        ctx.path === '/incoming-payments' ||
+        ctx.path === '/outgoing-payments' ||
+        ctx.path === '/quotes'
+      ) {
         ctx.walletAddressUrl = ctx.query['wallet-address'] as string
-      } else if (ctx.method === 'POST') {
-        ctx.walletAddressUrl = (ctx.request.body as CreateBody).walletAddress
+        console.log(ctx.walletAddressUrl)
```
Comment (njlie) [inline packages/backend/src/open_payments/wallet_address/middleware.ts:20]: Want to keep this console.log?

Comment (sabineschaller) [reply packages/backend/src/open_payments/wallet_address/middleware.ts]: Gone

File: packages/backend/src/open_payments/receiver/service.ts (hunk 6 above)
Comment (sabineschaller) [reply packages/backend/src/open_payments/receiver/service.ts:238]: Should we keep it to not forget?

File: packages/backend/src/open_payments/payment/incoming/routes.ts (hunk 5 above)
Comment (sabineschaller) [reply packages/backend/src/open_payments/payment/incoming/routes.ts:79]: I don't think so because if you can get a private one, you've already gone through the auth flow.
