### PR TITLE
fix(backend): fix introspect call

### LINKED ISSUE #1002: Adding introspection package breaks creating incoming payment
- #960

broke the Postman demo (Demo with Signatures). I can request and receive a grant to create an incoming payment but when I send the request to actually create the incoming payment, I receive an Internal Server Error. The logs print
```
$ docker logs local-peer-backend-1                                                                                                                                         
{"level":30,"time":1674131143494,"pid":1,"hostname":"b1d9df5f9637","msg":"creating knex"}
info(message_bus): connected to replica 0
{"level":40,"time":1674131145051,"pid":1,"hostname":"b1d9df5f9637","path":"/jwks.json","method":"get","msg":"unexpected path/method"}
{"level":30,"time":1674131145190,"pid":1,"hostname":"b1d9df5f9637","msg":"Admin listening on 3001"}
{"level":30,"time":1674131145191,"pid":1,"hostname":"b1d9df5f9637","msg":"Open Payments listening on 80"}
{"level":30,"time":1674131145191,"pid":1,"hostname":"b1d9df5f9637","msg":"Connector listening on 3002"}
{"level":30,"time":1674131145191,"pid":1,"hostname":"b1d9df5f9637","msg":"🐒 has 🚀. Get ready for 🍌🍌🍌🍌🍌"}
{"level":50,"time":1674131153607,"pid":1,"hostname":"b1d9df5f9637","args":"96A406CE37670106D8D4","msg":"Error when making introspection request: Request failed with status code 415"}
err= Error: Error when making introspection request: Request failed with status code 415
    at introspectToken (/workspace/packages/token-introspection/dist/client/introspection.js:41:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /workspace/packages/backend/dist/open_payments/auth/middleware.js:35:31
    at async /workspace/packages/openapi/dist/middleware.js:17:17
    at async /workspace/packages/backend/dist/open_payments/payment_pointer/middleware.js:16:9
    at async bodyParser (/workspace/node_modules/.pnpm/koa-bodyparser@4.3.0/node_modules/koa-bodyparser/index.js:95:5)

  InternalServerError: Internal Server Error
      at Object.throw (/workspace/node_modules/.pnpm/koa@2.14.1/node_modules/koa/lib/context.js:97:11)
      at /workspace/packages/openapi/dist/middleware.js:35:26
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async /workspace/packages/backend/dist/open_payments/payment_pointer/middleware.js:16:9
      at async bodyParser (/workspace/node_modules/.pnpm/koa-bodyparser@4.3.0/node_modules/koa-bodyparser/index.js:95:5)
```

### PR DESCRIPTION
**Pull request by wilsonianb**
## Changes proposed in this pull request

- 

## Context

- fixes #1002 

## Checklist

- [x] Related issues linked using `fixes #number`
- [x] Tests added/updated
- [ ] Documentation added
- [x] Make sure that all checks pass

### CODE REVIEW

File: packages/token-introspection/src/client/index.ts [hunk 1]
```diff
@@ -49,7 +49,6 @@ export const createAxiosInstance = (args: {
     method: 'post',
     timeout: args.requestTimeoutMs
   })
-  axiosInstance.defaults.headers.common['Content-Type'] = 'application/json'
```
Comment (mkurapov) [inline packages/token-introspection/src/client/index.ts:52]: removing because it is default already?

File: packages/backend/src/open_payments/auth/middleware.ts [hunk 2]
```diff
@@ -56,7 +56,9 @@ export function createTokenIntrospectionMiddleware({
       )
       let tokenInfo: TokenInfo
       try {
-        tokenInfo = await tokenIntrospectionClient.introspect(token)
+        tokenInfo = await tokenIntrospectionClient.introspect({
```
Comment (mkurapov) [inline packages/backend/src/open_payments/auth/middleware.ts:59]: Let's add the TokenIntrospection `Client` interface to `interface AppServices`, so we have proper types when resolving this dependency

File: packages/token-introspection/src/client/index.ts (hunk 1 above)
Comment (wilsonianb) [reply packages/token-introspection/src/client/index.ts:52]: I removed it because

1. it should've been `axiosInstance.defaults.headers.post['Content-Type'] = 'application/json'`
2. axios automatically uses `'application/json'` when the body is an object, which is now the case

File: packages/backend/src/open_payments/auth/middleware.ts (hunk 2 above)
Comment (wilsonianb) [reply packages/backend/src/open_payments/auth/middleware.ts:59]: :+1: Thanks
You've resolved my confusion https://github.com/interledger/rafiki/issues/1002#issuecomment-1397260511

Comment (mkurapov) [reply packages/backend/src/open_payments/auth/middleware.ts:59]: I wish `container.singleton()` automagically did that already

**Review by mkurapov — APPROVED** [review]
