### PR TITLE
fix(point-of-sale): added bruno script + added missing env variables to local docker compose file

### LINKED ISSUE #3542: [POS Service] Bruno collection entry to initiate payment
POST /payment

### LINKED ISSUE #3619: [Local Playground] Add required env vars to POS and Card Services in Local Playground
The POS and Card services are failing to start up in the local playground environment due to their respective `docker-compose.yml` files not having some required environment variables configured:

* TENANT_ID
* TENANT_SECRET
* GRAPHQL_URL

The tenant id and secret can be configured to use the operator tenant id and secret for the corresponding backend service.

### PR DESCRIPTION
**Pull request by oana-lolea**
Added bruno script to initiate a payment.
Fixes #3542 
Linear [#1120](https://linear.app/interledger/issue/RAF-1120/pos-service-bruno-collection-entry-to-initiate-payment)

Also fixed the flow in the payment route. 
Linear [#1151](https://linear.app/interledger/issue/RAF-1151/pos-service-use-merchant-wallet-address-for-incoming-payment-creation)

Also added environment variables for POS and Cards services in local playground.
Fixes #3619 
Linear [#1150](https://linear.app/interledger/issue/RAF-1150/local-playground-add-required-env-vars-to-pos-and-card-services-in)

### CODE REVIEW

File: bruno/collections/Rafiki/POS Service APIs/Initiate Payment.bru [hunk 1]
```diff
@@ -0,0 +1,24 @@
...
+post {
+  url: http://localhost:3008/payment
+  body: json
+  auth: inherit
+}
+
+body:json {
+  {
+    "card": {
+      "walletAddress": "http://localhost:3000/accounts/gfranklin",
```
Comment (mkurapov) [inline bruno/collections/Rafiki/POS Service APIs/Initiate Payment.bru]: I believe we should be passing in `https://cloud-nine-wallet/...` here, since the POS service will get it in the request and should find the wallet address using the shared rafiki network set up in the docker compose

File: packages/backend/src/app.ts [hunk 2]
```diff
@@ -454,7 +454,7 @@ export class App {
     // For tests, we still need to get the tenant in the middleware, but
     // we don't need to verify the signature nor prevent replay attacks
     koa.use(
-      this.config.env !== 'test'
+      this.config.env !== 'test' && this.config.env !== 'development'
```
Comment (oana-lolea) [inline packages/backend/src/app.ts]: Added this so that I can bypass the tenant signature check for now while testing

File: packages/point-of-sale/src/payments/routes.ts [hunk 3]
```diff
@@ -73,7 +74,8 @@ async function payment(
     }
     const incomingPayment = await deps.paymentService.createIncomingPayment(
       walletAddress.id,
```
Comment (oana-lolea) [inline packages/point-of-sale/src/payments/routes.ts]: This needs to be the UUID of the wallet address, not the actual address. Will add a request to fetch that.

File: bruno/collections/Rafiki/POS Service APIs/Initiate Payment.bru [hunk 4]
```diff
@@ -0,0 +1,24 @@
+meta {
+  name: Initiate Payment
+  type: http
+  seq: 3
+}
+
+post {
+  url: http://localhost:3008/payment
```
Comment (mkurapov) [inline bruno/collections/Rafiki/POS Service APIs/Initiate Payment.bru]:
```suggestion
  url: http://localhost:4008/payment
```
Let's do this, such that the incoming payment will be on the happy-life side of things, and cloud nine will pay into it.

File: packages/point-of-sale/src/payments/service.ts [hunk 5]
```diff
@@ -66,23 +67,32 @@ export function createPaymentService(
...
+        expiresAt
+      }
+    },
+    ...(tenantId && {
+      context: {
+        headers: {
+          'tenant-id': tenantId
+        }
+      }
+    })
```
Comment (mkurapov) [inline packages/point-of-sale/src/payments/service.ts]: We are already passing in the `tenantId` when we are setting up the `apolloClient` (`index.ts`), so I think we can leave this out

File: localenv/cloud-nine-wallet/docker-compose.yml [hunk 6]
```diff
@@ -23,6 +23,10 @@ services:
       LOG_LEVEL: debug
       CARD_SERVICE_PORT: 3007
       DATABASE_URL: postgresql://cloud_nine_wallet_card_service:cloud_nine_wallet_card_service@shared-database/cloud_nine_wallet_card_service
+      GRAPHQL_URL: http://cloud-nine-wallet-backend:3001/graphql
+      TENANT_ID: 438fa74a-fa7d-4317-9ced-dde32ece1787
+      TENANT_SECRET: tenant_secret
+      TENANT_SIGNATURE_VERSION: tenant_signature_version
```
Comment (mkurapov) [inline localenv/cloud-nine-wallet/docker-compose.yml]:
```suggestion
      TENANT_SIGNATURE_VERSION: 1
```

File: packages/point-of-sale/src/card-service-client/client.ts [hunk 7]
```diff
@@ -88,9 +88,8 @@ async function sendPayment(
       ...options,
       requestId: uuid()
     }
-    const cardServiceUrl = options.card.walletAddress.cardService
     const response = await deps.axios.post<PaymentResponse>(
```
Comment (oana-lolea) [inline packages/point-of-sale/src/card-service-client/client.ts:91]: Will get `BAD_REQUEST` because we are missing some data that `cardService` is expecting.

File: localenv/cloud-nine-wallet/docker-compose.yml [hunk 8]
```diff
@@ -11,6 +11,7 @@ services:
       - rafiki
     ports:
       - '3007:3007'
+      - '9234:9229'
```
Comment (oana-lolea) [inline localenv/cloud-nine-wallet/docker-compose.yml:14]: Added for debugging

File: localenv/happy-life-bank/docker-compose.yml [hunk 9]
```diff
@@ -44,6 +48,7 @@ services:
       - rafiki 
     ports: 
       - '4008:4008' 
+      - '9233:9229'
```
Comment (oana-lolea) [inline localenv/happy-life-bank/docker-compose.yml:51]: Added for debugging

File: localenv/cloud-nine-wallet/docker-compose.yml [hunk 10]
```diff
@@ -23,6 +24,10 @@ services:
       LOG_LEVEL: debug
       CARD_SERVICE_PORT: 3007
       DATABASE_URL: postgresql://cloud_nine_wallet_card_service:cloud_nine_wallet_card_service@shared-database/cloud_nine_wallet_card_service
+      GRAPHQL_URL: http://cloud-nine-wallet-backend:3001/graphql
+      TENANT_ID: 438fa74a-fa7d-4317-9ced-dde32ece1787
+      TENANT_SECRET: tenant_secret
```
Comment (mkurapov) [inline localenv/cloud-nine-wallet/docker-compose.yml]: `TENANT_SECRET` should match the `API_SECRET` from `backend` container

File: packages/backend/src/app.ts (hunk 2 above)
Comment (mkurapov) [reply packages/backend/src/app.ts]: I think if the `TENANT_SECRET` matches the `API_SECRET` from above, then this validation should work without having to bypass it

File: packages/point-of-sale/src/payments/service.ts [hunk 11]
```diff
@@ -72,20 +77,22 @@ const createIncomingPayment: FnWithDeps<
     Date.now() + deps.config.incomingPaymentExpiryMs
   ).toISOString()
   const { data } = await client.mutate<
-    Mutation['createIncomingPayment'],
-    CreateIncomingPaymentInput
+    Mutation,
```
Comment (mkurapov) [inline packages/point-of-sale/src/payments/service.ts]:
```suggestion
    CreateIncomingPayment,
```

Importing this from `'../graphql/generated/graphql'` should give you the correct type for the Mutation

**Review by mkurapov — APPROVED** [review]
