### PR TITLE
fix(wallet-address)!: additional properties

### LINKED ISSUE #2874: Fix wallet address additional properties
## Context

Currently, if we have a wallet address with additional properties, when we fetch it via Open Payments, we end up exposing the whole additional property DB object in the response:

```
{
  "id": "https://rafiki.vuza.finance/collins-test-wallet",
  "publicName": "collins-test-wallet",
  "assetCode": "USD",
  "assetScale": 2,
  "authServer": "http://rafiki.vuza.finance:3006",
  "resourceServer": "https://rafiki.vuza.finance",
  "additionalProperties": [
    {
      "id": "5639c8c5-d88b-48b6-887a-43172c6acc88",
      "fieldKey": "0",
      "fieldValue": "first",
      "visibleInOpenPayments": true,
      "walletAddressId": "c280c557-351a-4312-9aa2-e32bbc8346a8",
      "createdAt": "2024-08-19T18:42:51.092Z",
      "updatedAt": "2024-08-19T18:42:51.092Z"
    }
  ]
}
```

Instead, we should properly parse the response, such that it looks like:

```
{
  "id": "https://rafiki.vuza.finance/collins-test-wallet",
  "publicName": "collins-test-wallet",
  "assetCode": "USD",
  "assetScale": 2,
  "authServer": "http://rafiki.vuza.finance:3006",
  "resourceServer": "https://rafiki.vuza.finance",
  "additionalProperties": {
      "0": "first"
    }
}
```

## Todos
- [x] Fix how we display wallet address additional properties when fetching via Open Payments

### PR DESCRIPTION
**Pull request by golobitch**
## Changes proposed in this pull request

- Do not expose all the additional properties field, but just key and value

## Context

fixes #2874 

## Checklist

- [x] Related issues linked using `fixes #number`
- [x] Tests added/updated
- [ ] Documentation added
- [x] Make sure that all checks pass
- [ ] Bruno collection updated

### CODE REVIEW

File: packages/backend/src/open_payments/wallet_address/model.ts [hunk 1]
```diff
@@ -121,7 +121,14 @@ export class WalletAddress
       resourceServer
     }
     if (this.additionalProperties && this.additionalProperties.length) {
-      returnVal.additionalProperties = this.additionalProperties
+      returnVal.additionalProperties = this.additionalProperties.reduce(
```
Comment (mkurapov) [inline packages/backend/src/open_payments/wallet_address/model.ts:124]: we should filter out properties that are not `visibleInOpenPayments`

**Review by mkurapov — APPROVED** [review]
