### PR TITLE
fix(interledger): support more asset/amount transfer combinations

### LINKED ISSUE #118: Support same asset code, different scale transfers
The accounts service doesn't correctly handle transfers between accounts with the same asset code but different asset scales:
https://github.com/interledger/rafiki/blob/main/packages/interledger/src/accounts/service.ts#L935-L945
It currently treats them as identical assets.

### LINKED ISSUE #119: Support same asset transfers with different source and destination amounts
via that asset's liquidity account

### PR DESCRIPTION
**Pull request by wilsonianb**
## Changes proposed in this pull request

- support same asset code, different scale transfers
- support same asset, different amounts transfers

## Context

fixes #118 
fixes #119 

## Checklist

- [x] Related issues linked using `fixes #number`
- [x] Tests added/updated
- [ ] Documentation added
- [x] Make sure that all checks pass

### CODE REVIEW

File: packages/interledger/src/accounts/service.ts [hunk 1]
```diff
@@ -932,17 +932,39 @@ export class AccountsService implements AccountsServiceInterface {
...
+      sourceAccount.asset.code === destinationAccount.asset.code &&
+      sourceAccount.asset.scale === destinationAccount.asset.scale
+    ) {
       transfers.push({
         id: randomId(),
         sourceBalanceId: sourceAccount.balanceId,
         destinationBalanceId: destinationAccount.balanceId,
-        amount: sourceAmount,
+        amount:
+          destinationAmount && destinationAmount < sourceAmount
```
Comment (sentientwaffle) [inline packages/interledger/src/accounts/service.ts:944]: maybe `Math.min(sourceAmount, destinationAmount ?? Infinity)` would be clearer?

Comment (wilsonianb) [reply packages/interledger/src/accounts/service.ts:944]: Yeah, I had tried `Math.min` but it sounds like it won't work for `BigInt`s

Comment (sentientwaffle) [reply packages/interledger/src/accounts/service.ts:944]: ah, right, nevermind then

**Review by sentientwaffle — APPROVED** [review]
