### PR TITLE
chore(bruno): fix Peer to Peer example requests

### LINKED ISSUE #2700: Fix Peer-to-Peer examples in Bruno collection
## Context
Currently, we are unable to run the Bruno Peer-to-Peer example requests, as they fail on the Create Quote request. This is due to the fact that with the introduction of 
- #2596

we are requiring a signature on the Admin API requests to be present. 

## Todos
- [ ] Fix Bruno Peer-to-Peer Create Quote request by adding a signature to the request

### PR DESCRIPTION
**Pull request by mkurapov**
## Changes proposed in this pull request

- Fix `createQuote` requests in Peer to Peer bruno examples by adding `signature` header
- Tidy up bruno scripts
- Fix broken link in doc

## Context

Fixes #2700 

## Checklist

- [x] Related issues linked using `fixes #number`
- [ ] Tests added/updated
- [x] Documentation added
- [ ] Make sure that all checks pass
- [x] Bruno collection updated

### CODE REVIEW

File: bruno/collections/Rafiki/scripts.js [hunk 1]
```diff
@@ -127,7 +129,9 @@ const scripts = {
     bru.setEnvVar('tokenId', body?.access_token?.manage.split('/').pop())
   },
 
-  getWalletAddressId: async function (host, publicName, varName) {
+  loadWalletAddressIdsIntoVariables: async function () {
+    const requestUrl = this.resolveTemplateVariables(req.url)
```
Comment (mkurapov) [inline bruno/collections/Rafiki/scripts.js:133]: now, we just load up all of the walletAddressIds into variables for the respective Admin API that was called

File: bruno/collections/Rafiki/environments/Local Playground.bru [hunk 2]
```diff
@@ -14,4 +14,12 @@ vars {
...
   apiSignatureSecret: iyIgCprjb9uL8wFckR+pLEkJWMB7FJhgkvqhTQR/964=
   assetId: USD
+  gfranklinWalletAddress: https://cloud-nine-wallet-backend/accounts/gfranklin
+  bhamchestWalletAddress: https://cloud-nine-wallet-backend/accounts/bhamchest
+  wbdcWalletAddress: https://cloud-nine-wallet-backend/accounts/wbdc
+  pfryWalletAddress: https://happy-life-bank-backend/accounts/pfry
+  planexWalletAddress: https://happy-life-bank-backend/accounts/planex
+  asmithWalletAddress: https://happy-life-bank-backend/accounts/asmith
+  larsWalletAddress: https://happy-life-bank-backend/accounts/lars
+  davidWalletAddress: https://happy-life-bank-backend/accounts/david
```
Comment (mkurapov) [inline bruno/collections/Rafiki/environments/Local Playground.bru:24]: if they dont seem useful, we can also just remove these entirely from here and remove the `brunoEnvVar` in the seed files

**Comment by BlairCurrey** [comment]
Just a related observation: Integration tests could have caught this if they signed the requests. Maybe they should (out of scope here though of course). At that point they are looking more and more like E2E tests I guess (I have went back and forth on that so many times 🤪).

File: bruno/collections/Rafiki/environments/Local Playground.bru (hunk 2 above)
Comment (BlairCurrey) [reply bruno/collections/Rafiki/environments/Local Playground.bru:24]: I guess im not quite following... these are the wallet address id's that we are setting in `loadWalletAddressIdsIntoVariables` right? Why would we even need to do `loadWalletAddressIdsIntoVariables` ? I would prefer the explicitness of setting them here but I'm probably missing something (harder to handle all environments, like rafiki money, or??)

**Review by BlairCurrey — APPROVED** [review]
Worked for me locally. Left a comment seeking some clarification but overall I think it looks good.

File: bruno/collections/Rafiki/environments/Local Playground.bru (hunk 2 above)
Comment (mkurapov) [reply bruno/collections/Rafiki/environments/Local Playground.bru:24]: The walletAddressIds are the local UUIDs for the wallet addresses in each corresponding rafiki instance. It would (probably) be nice to be able to use walletAddressUrls instead of the UUIDs in Admin API mutations, but as we have it now, it's what we have to do
