### PR TITLE
chore(backend): fix incrementCounterWithTransactionAmount function

### LINKED ISSUE #3145: Fix transaction amount total telemetry collection
## Context
- Since we introduced #2857, telemetry is not collected for the `packet_amount_fulfill` metric. This is because the `telemetryService.incrementCounterWithTransactionAmount` function is not properly passing in the converted amount into the `incrementCounter` function

## Todos
- [ ] Fix the `telemetryService.incrementCounterWithTransactionAmount` function

### PR DESCRIPTION
**Pull request by mkurapov**
## Changes proposed in this pull request

- Fix incrementCounterWithTransactionAmount metric collection

## Context

Fixes #3145 

## Checklist

- [x] Related issues linked using `fixes #number`
- [x] Tests added/updated
- [ ] Make sure that all checks pass
- [ ] Bruno collection updated (if necessary)
- [ ] Documentation issue created with `user-docs` label (if necessary)
- [ ] OpenAPI specs updated (if necessary)

### CODE REVIEW

File: packages/backend/src/telemetry/service.ts [hunk 1]
```diff
@@ -173,14 +173,13 @@ export class TelemetryServiceImpl implements TelemetryService {
         return
       }
 
-      const obfuscatedAmount = preservePrivacy
-        ? privacy.applyPrivacy(Number(converted))
-        : Number(converted)
-      this.incrementCounter(name, obfuscatedAmount, attributes)
+      const finalAmount = preservePrivacy
+        ? privacy.applyPrivacy(Number(converted.amount))
```
Comment (BlairCurrey) [inline packages/backend/src/telemetry/service.ts:177]: ah man... `Number` takes anything.

**Review by BlairCurrey — APPROVED** [review]
🙏

File: packages/backend/src/telemetry/service.ts (hunk 1 above)
Comment (mkurapov) [reply packages/backend/src/telemetry/service.ts:177]: Definitely feels like it should take in some proper types instead...
