### PR TITLE
fix(backend): made CARD_SERVICE_URL optional

### LINKED ISSUE #3577: [Backend] Make CARD_SERVICE_URL env optional
Not every Rafiki operator will want to enable cards, so it should be able to launch the backend without having the `CARD_SERVICE_URL` env variable configured.

Likewise, we should not display the `cardServiceUrl` under each `walletAddress` when it is fetched using Open Payments.

### PR DESCRIPTION
**Pull request by oana-lolea**
## Changes proposed in this pull request

- `CARD_SERVICE_URL` is now optional
- `OpenPaymentsWalletAddress` does not return `cardServiceUrl` if it's not set

## Context

Fixes #3577 
Linear [#1113](https://linear.app/interledger/issue/RAF-1134/backend-make-card-service-url-env-optional)

## Checklist

- [ ] Related issues linked using `fixes #number`
- [ ] Tests added/updated
- [ ] Make sure that all checks pass
- [ ] Bruno collection updated (if necessary)
- [ ] Documentation issue created with `user-docs` label (if necessary)
- [ ] OpenAPI specs updated (if necessary)

### CODE REVIEW

File: packages/backend/src/index.ts [hunk 1]
```diff
@@ -672,13 +672,16 @@ export function initIocContainer(
     })
   })
 
-  container.singleton('cardService', async (deps) => {
-    return createCardService({
-      axios: await deps.use('axios'),
-      logger: await deps.use('logger'),
-      cardServiceUrl: config.cardServiceUrl
+  if (config.cardServiceUrl) {
```
Comment (mkurapov) [inline packages/backend/src/index.ts]: Let's remove this `if` and keep the `cardService` service defined, otherwise we might get unexpected behaviour if a singleton resolves to undefined.

Comment (mkurapov) [reply packages/backend/src/index.ts]: We can do a `NoopCardService` (similar to the `NoopTelemetryService`)

File: packages/backend/src/card/service.ts [hunk 2]
```diff
@@ -36,6 +36,14 @@ export async function createCardService(
   }
 }
 
+export async function createNoopCardService(): Promise<CardService> {
+  return {
+    async sendPaymentEvent(_eventDetails) {
+      // do nothing
```
Comment (mkurapov) [inline packages/backend/src/card/service.ts:44]: Let's have a `warn` log here.
