### PR TITLE
fix: match payment bodies for pos and card service

### LINKED ISSUE #3622: [POS Service/Card Service] Reconcile request bodies for `POST /payment`
The shape of the `POST /payment` request body made by the POS service to card service and the OpenAPI spec for that request body on the card service differ, causing the request to fail.

* Update POS Service `POST /payment` call to the card service to use correct request body 
* `cardServiceClient.sendPayment` should probably have another parameter to pass in the card service url to use, separate from the payment options

### PR DESCRIPTION
**Pull request by oana-lolea**
## Changes proposed in this pull request

- Matched `POST /payment` bodies for `point-of-sale` and `card-service` (removed unnecessary fields)
- Fixed some GraphQL calls
- Updated OpenAPI spec for 'card-service'

## Context

Fixes #3622 
Linear [#1153](https://linear.app/interledger/issue/RAF-1153/pos-servicecard-service-reconcile-request-bodies-for-post-payment)

## Checklist

- [x] Related issues linked using `fixes #number`
- [x] Tests added/updated
- [ ] Make sure that all checks pass
- [x] Bruno collection updated (if necessary)
- [ ] Documentation issue created with `user-docs` label (if necessary)
- [x] OpenAPI specs updated (if necessary)

### CODE REVIEW

File: packages/card-service/src/payment/service.ts [hunk 1]
```diff
@@ -64,22 +64,23 @@ async function handleCreatePayment(
...
-          expiry: payment.card.expiry
+        input: {
+          walletAddressId,
+          incomingPayment: payment.incomingPaymentUrl,
+          cardDetails: {
+            signature: payment.card.signature
+          }
         }
       }
     })
```
Comment (oana-lolea) [inline packages/card-service/src/payment/service.ts:86]: It fails at `waitForPaymentEvent`

File: packages/card-service/src/payment/service.ts [hunk 2]
```diff
@@ -54,8 +54,8 @@ async function handleCreatePayment(
   try {
     const deferred = new Deferred<PaymentEventBody>()
     paymentWaitMap.set(requestId, deferred)
-    const walletAddressByUrl = await deps.apolloClient.query<
-      Query['walletAddressByUrl'],
+    const { data } = await deps.apolloClient.query<
+      Query,
```
Comment (mkurapov) [inline packages/card-service/src/payment/service.ts]:
```suggestion
      GetWalletAddressByUrl,
```

File: packages/card-service/src/payment/service.ts [hunk 3]
```diff
@@ -64,22 +64,23 @@ async function handleCreatePayment(
...
+    if (!data?.walletAddressByUrl) {
       throw new UnknownWalletAddressError()
     }
-    const walletAddressId = walletAddressByUrl.data.id
+    const walletAddressId = data.walletAddressByUrl.id
 
     const outgoingPaymentFromIncomingPayment = await deps.apolloClient.mutate<
-      Mutation['createOutgoingPaymentFromIncomingPayment'],
-      CreateOutgoingPaymentFromIncomingPaymentInput
+      Mutation,
```
Comment (mkurapov) [inline packages/card-service/src/payment/service.ts]:
```suggestion
      CreateOutgoingPaymentFromIncoming,
```
allowing for the types to work for the response

**Review by mkurapov — APPROVED** [review]
