### PR TITLE
fix(backend): allow admin api to query all receivers and move checks

### LINKED ISSUE #3253: Allow querying completed and expired receivers (incoming payments)
## Context
In our backend GraphQL Admin API, we have a `receiver` [query](https://rafiki.dev/apis/graphql/backend/queries/#receiver). It allows fetching a "local" incoming payment or a remote incoming payment, which is fetched at a different Rafiki instance using Open Payments.

Currently, the `receiver` query returns a payment _only_ if it hasn't been completed yet. This is not the intended behaviour. 

### Expected behaviour
We should be able to fetch a receiver (local or remote incoming payment), even if it has already been completed. 

The logic that needs to be changed is in the `Receiver` class, as we do not allow constructing a new `Receiver` instance from a payment that has been completed, expired, or has an empty `methods` array. We need to move those checks from inside the constructor directly to the places where they are needed (like during quote creation or outgoing payment processing).

## Todos
- [ ] Allow creating `Receiver` instances even if the payment is completed, expired, or has an empty methods array
- [ ] Move those checks to the correct places where they are needed
- [ ] Make sure the `receiver` Admin API query returns incoming payments even if they are completed or expired

### PR DESCRIPTION
**Pull request by cozminu**
## Changes proposed in this pull request

- moved validation checks (completed, expired and methods availability) to createOutgoingPayment, handleSending, resolveReceiver via `Resolver.isInvalidExpiredOrCompleted`

## Context

fixes #3253 

## Checklist

- [ ] Related issues linked using `fixes #number`
- [ ] Tests added/updated
- [ ] Make sure that all checks pass
- [ ] Bruno collection updated (if necessary)
- [ ] Documentation issue created with `user-docs` label (if necessary)
- [ ] OpenAPI specs updated (if necessary)

### CODE REVIEW

**Comment by cozminu** [comment]
tests tbd after review

File: packages/backend/src/open_payments/receiver/model.ts [hunk 1]
```diff
@@ -120,4 +108,30 @@ export class Receiver {
       requestCounter: Counter.from(0) as Counter
     }
   }
+
+  public static isInvalidExpiredOrCompleted(
```
Comment (BlairCurrey) [inline packages/backend/src/open_payments/receiver/model.ts:112]: Does this need to be a static method? Or can we just make it a regular method, and use `this` to refer to the receiver instead of passing it in? This allows us to not import the `Receiver` model across our different services and leverages the receiver instance we already have. 

Then instead of handling `undefined` in this method we check where this is called like:

So this:

```ts
      if (!receiver || receiver.isInvalidExpiredOrCompleted()) {
        throw OutgoingPaymentError.InvalidQuote
      }
```
Instead of

```ts
      if (Receiver.isInvalidExpiredOrCompleted(receiver)) {
        throw OutgoingPaymentError.InvalidQuote
      }
```

File: packages/backend/src/open_payments/receiver/model.ts [hunk 2]
```diff
@@ -120,4 +108,30 @@ export class Receiver {
...
+      incomingPayment.expiresAt &&
+      incomingPayment.expiresAt.getTime() <= Date.now()
+    ) {
+      // throw new Error('Cannot create receiver from expired incoming payment')
+      return true
+    }
+    if (!incomingPayment.methods.length) {
+      // throw new Error('Missing payment method(s) on incoming payment')
+      return true
+    }
```
Comment (BlairCurrey) [inline packages/backend/src/open_payments/receiver/model.ts:133]: We can probably remove this payment method check. Its not going to do anything because the `Receiver` constructor will error if it's empty. It looks for ilp method then throws if it cant find it.

I am considering if it should be returned to the constructor but it seems kind of redundant in the first place. With or without a check for this, if method is empty, it will error as described here (missing ilp payment method). I guess the `method.length` check was just slightly more informative. I think just remove it here.

File: packages/backend/src/open_payments/receiver/model.ts [hunk 3]
```diff
@@ -120,4 +108,30 @@ export class Receiver {
       requestCounter: Counter.from(0) as Counter
     }
   }
+
+  public static isInvalidExpiredOrCompleted(
+    receiver: Receiver | undefined
+  ): receiver is undefined {
```
[the remark this answers is not in the document]
Comment (cozminu) [reply packages/backend/src/open_payments/receiver/model.ts]: first time around I did it, typescript response was boolean
```
public static isActive(receiver: Receiver | undefined): boolean {
```
the issue was that I had to double check for type:
Screenshot 2025-02-25 at 10 38 03

but if we do the non-static method, then we won't have this problem

File: packages/backend/src/open_payments/receiver/model.ts (hunk 2 above)
Comment (cozminu) [reply packages/backend/src/open_payments/receiver/model.ts]: moved to constructor for now because it makes more sense since there's already a check there and ILP method is hard-coupled to the Receiver via `ilpAddress` property.
Checked if this will affect querying the receiver via Admin API and it doesn't.

File: packages/backend/src/open_payments/receiver/model.ts (hunk 1 above)
Comment (cozminu) [reply packages/backend/src/open_payments/receiver/model.ts]: It does not, I chose static for simplicity only. Changed to non-static method.

File: packages/backend/src/open_payments/receiver/model.ts (hunk 3 above)
[the remark this answers is not in the document]
Comment (BlairCurrey) [reply packages/backend/src/open_payments/receiver/model.ts]: That makes sense, I see how its working now.

File: packages/backend/src/payment-method/ilp/stream-credentials/service.ts [hunk 4]
```diff
@@ -33,9 +33,6 @@ function getStreamCredentials(
   deps: ServiceDependencies,
   payment: IncomingPayment
 ): IlpStreamCredentials | undefined {
-  if (payment.isExpiredOrComplete()) {
```
Comment (njlie) [inline packages/backend/src/payment-method/ilp/stream-credentials/service.ts:36]: `IncomingPayment.isExpiredOrComplete()` isn't used anywhere else in the code with this deletion - perhaps it can be cleaned up?

File: packages/backend/src/open_payments/receiver/model.ts [hunk 5]
```diff
@@ -120,4 +108,28 @@ export class Receiver {
...
     }
   }
+
+  public static isActive(receiver: Receiver | undefined): receiver is Receiver {
+    if (!receiver) {
+      return false
+    }
+    const incomingPayment = receiver.incomingPayment
+    if (incomingPayment.completed) {
+      // throw new Error('Cannot create receiver from completed incoming payment')
```
Comment (njlie) [inline packages/backend/src/open_payments/receiver/model.ts:118]: nit: clean up comments

File: packages/backend/src/open_payments/receiver/service.test.ts [hunk 6]
```diff
@@ -251,7 +251,7 @@ describe('Receiver Service', (): void => {
         expect(remoteIncomingPaymentServiceGetSpy).toHaveBeenCalledTimes(1)
       })
 
-      test('returns undefined if error getting receiver from remote incoming payment', async () => {
+      test('gets receiver from completed remote incoming payment', async () => {
         const mockedIncomingPayment = mockIncomingPaymentWithPaymentMethods({
           completed: true // cannot get receiver with a completed incoming payment
```
Comment (mkurapov) [inline packages/backend/src/open_payments/receiver/service.test.ts:256]:
```suggestion
          completed: true
```

File: packages/backend/src/payment-method/ilp/stream-credentials/service.ts (hunk 4 above)
Comment (mkurapov) [reply packages/backend/src/payment-method/ilp/stream-credentials/service.ts:36]: Given this, we should update the `receiverService.getLocalIncomingPayment` function to not error if we could not get stream credentials for the payment.

**Review by mkurapov — APPROVED** [review]

File: packages/backend/src/open_payments/receiver/model.ts [hunk 7]
```diff
@@ -35,29 +35,17 @@ export class Receiver {
...
       ? parseAmount(incomingPayment.incomingAmount)
       : undefined
     const receivedAmount = parseAmount(incomingPayment.receivedAmount)
 
     // TODO: handle multiple payment methods
-    const ilpMethod = incomingPayment.methods.find(
+    const ilpMethod = incomingPayment.methods?.find(
       (method) => method.type === 'ilp'
     )
     if (!ilpMethod) {
```
Comment (mkurapov) [inline packages/backend/src/open_payments/receiver/model.ts:51]: Maybe we should be a bit more permissive here, and _not_ throw if there are no payment methods provided. (we can keep the check for invalid ilp address - if payment method exists).  What do you think?

**Review by njlie — APPROVED** [review]
