### PR TITLE
fix(backend): support SPSP queries

### LINKED ISSUE #439: Support SPSP queries to stream connection endpoints
https://docs.openpayments.guide/reference/get-ilp-stream-connection

To allow web monetization payments to incoming payments.

### LINKED ISSUE #1030: SPSP query fails OpenAPI validation
running localenv:
```
$ curl  'http://localhost:3000/accounts/gfranklin' -H 'accept: application/spsp4+json' -H 'host: backend' 
must accept json
```
That error is presumably from `createValidatorMiddleware`, which shouldn't be used when handling an SPSP query
https://github.com/interledger/rafiki/blob/3968ae347743e1c05ae19c7bcd0f559655cbd5d6/packages/backend/src/app.ts#L381-L400

related to:
- https://github.com/interledger/rafiki/issues/439

### PR DESCRIPTION
**Pull request by wilsonianb**
## Changes proposed in this pull request

- allow SPSP queries to both payment pointers and Open Payments connections

## Context

- fixes #1030 
- fixes #439 

## Checklist

- [x] Related issues linked using `fixes #number`
- [x] Tests added/updated
- [ ] Documentation added
- [x] Make sure that all checks pass

### CODE REVIEW

File: packages/backend/src/spsp/routes.ts [hunk 1]
```diff
@@ -46,18 +45,15 @@ async function getPay(
 
   try {
     const { ilpAddress, sharedSecret } = deps.streamServer.generateCredentials({
```
Comment (wilsonianb) [inline packages/backend/src/spsp/routes.ts:47]: Existential question:
Do `routes.ts` files need `ServiceDependencies` if they can just access things via
```suggestion
    const streamServer = await ctx.container.use('streamServer')
    const { ilpAddress, sharedSecret } = streamServer.generateCredentials({
```

File: packages/backend/src/app.ts [hunk 2]
```diff
@@ -329,6 +334,30 @@ export class App {
...
+                    const incomingPayment =
+                      await incomingPaymentService.getByConnection(
+                        ctx.params.id
+                      )
+                    if (!incomingPayment) return ctx.throw(404)
+                    ctx.paymentTag = incomingPayment.id
+                    ctx.asset = {
+                      code: incomingPayment.asset.code,
+                      scale: incomingPayment.asset.scale
+                    }
```
[the remark this answers is not in the document]
Comment (wilsonianb) [reply packages/backend/src/app.ts]: A little better
https://github.com/interledger/rafiki/pull/1032/commits/8ef3153a12954c3685840c91ec8ec07683523746

File: packages/backend/src/app.ts [hunk 3]
```diff
@@ -329,6 +338,23 @@ export class App {
               route = connectionRoutes.get
               router[method](
                 toRouterPath(path),
+                connectionMiddleware,
```
Comment (mkurapov) [inline packages/backend/src/app.ts:341]: this will be nicer once the magic for loop is gone (ie https://github.com/interledger/rafiki/issues/916)

File: packages/backend/src/spsp/routes.ts (hunk 1 above)
Comment (mkurapov) [reply packages/backend/src/spsp/routes.ts:47]: I wouldn't mind keeping `ServiceDependencies` for consistency IMO

File: packages/backend/src/open_payments/connection/middleware.ts [hunk 4]
```diff
@@ -0,0 +1,23 @@
+import { AppContext } from '../../app'
+import { IncomingPayment } from '../payment/incoming/model'
+
+export interface ConnectionContext extends AppContext {
+  incomingPayment: IncomingPayment
+}
+
+export const connectionMiddleware = async (
```
Comment (mkurapov) [inline packages/backend/src/open_payments/connection/middleware.ts:8]: 🤔 
since we would only need this if we are dealing with `application/spsp4+json`, maybe if we had the SPSP middleware in a function (ie the comment above), we could just do this incoming payment lookup directly in that method, within the `if (application/spsp4+json)` block?

**Review by mkurapov — DISMISSED** [review]
Looks good, a few considerations

File: packages/backend/src/open_payments/connection/middleware.ts (hunk 4 above)
Comment (wilsonianb) [reply packages/backend/src/open_payments/connection/middleware.ts:8]: `ctx.incomingPayment` is also used in the (non-SPSP) `ConnectionRoutes.get`

**Review by mkurapov — APPROVED** [review]
